version: 0.0
os: linux
files:
  - source: sourcecode 
    destination: /var/www/html/magento2/sourcecode/
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 1200
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 1200
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 600
      runas: root
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 600
      runas: root
